<?php

return [

    'sentinel' => require $app->getConfigurationDir().'/sentinel.php',
    'secret' => '0f45c7e965ccb2bc6fb06974912062fb3ab1d43f',

    'eloquent' => [
        'driver'    => $_SERVER['APP_DATABASE_DRIVER'],
        'host'      => $_SERVER['APP_DATABASE_HOST'],
        'database'  => $_SERVER['APP_DATABASE_DATABASE'],
        'username'  => $_SERVER['APP_DATABASE_USERNAME'],
        'password'  => $_SERVER['APP_DATABASE_PASSWORD'],
        'charset'   => $_SERVER['APP_DATABASE_CHARSET'],
        'collation' => $_SERVER['APP_DATABASE_COLLATION'],
        'prefix'    => $_SERVER['APP_DATABASE_PREFIX']
    ],

    'twig' => [
        'path' => [
            $app->getRootDir().'/templates'
        ],
        'options' => [
            'cache' => $app->getCacheDir().'/twig',
        ]
    ],

    'monolog' => [
        'name'  => 'app',
        'path'  => $app->getLogDir().'/'.$app->getEnvironment().'.log',
        'level' => Monolog\Logger::ERROR
    ],
    'rest' => [
        'prefix' => '/api', // All URLs generated with the RestRouter will be prefixed with this.
        'key'    => 'id', // Default key to use for single resources.
        /**
         * Default requirement for single resources key.
         * To disable it, use empty string ('') rather than null.
         */
        'requirement' => '[0-9]+',
        'crud' => [
            'get'               => true,
            'get_collection'    => true,
            'post'              => true,
            'put'               => true,
            'delete'            => true,
            'delete_collection' => false
        ]
    ],

    // The routes that should be generated by the CRUD method of the RestRouter.
    'cors' => [
        'origin'         => '*',
        'allow_headers'  => 'X-Requested-With, Content-Type, Accept, Origin, Authorization',
        'expose_headers' => 'Location, Content-Range',
        'methods'        => 'GET, POST, PUT, PATCH, DELETE',
        'max_age'        => 3600
    ],

    'jwt' => [
        'server_name'            => 'localhost', // The server name used to encrypt access tokens and refresh tokens.
        'access_token_lifetime'  => 36000, // seconds (1h)
        'refresh_token_lifetime' => 1209600 // seconds (14 days)
    ],

];
